apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
     longhorn:
       engine:
         repository: longhornio/longhorn-engine
         tag: v1.3.0
       manager:
         repository: longhornio/longhorn-manager
         tag: v1.3.0
       ui:
         repository: longhornio/longhorn-ui
         tag: v1.3.0
       instanceManager:
         repository: longhornio/longhorn-instance-manager
         tag: v1_20220611
       shareManager:
         repository: longhornio/longhorn-share-manager
         tag: v1_20230320
       backingImageManager:
         repository: longhornio/backing-image-manager
         tag: v3_20220609
     csi:
       attacher:
         repository: longhornio/csi-attacher
         tag: v3.4.0
       provisioner:
         repository: longhornio/csi-provisioner
         tag: v2.1.2
       nodeDriverRegistrar:
         repository: longhornio/csi-node-driver-registrar
         tag: v2.5.0
       resizer:
         repository: longhornio/csi-resizer
         tag: v1.2.0
       snapshotter:
         repository: longhornio/csi-snapshotter
         tag: v3.0.3
     pullPolicy: IfNotPresent
    persistence:
      defaultClassReplicaCount: 2
      defaultClass: false
    defaultSettings:
      backupTarget:  nfs://192.168.0.120:/data/backups/longhorn 
  valuesFrom:
    - kind: Secret
      name: longhorn-secrets
      valuesKey: longhorn-secrets.yaml
      optional: false
