apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: longhornio/longhorn-engine
      tag: v1.3.0
    persistence:
      defaultClassReplicaCount: 2
      defaultClass: false
    defaultSettings:
      backupTarget:  nfs://192.168.0.120:/data/backups/longhorn 
  valuesFrom:
    - kind: Secret
      name: longhorn-secrets
      valuesKey: longhorn-secrets.yaml
      optional: false  
